INSERT INTO exercise (id, name) VALUES
    (RANDOM_UUID(), 'Bench Press'),
    (RANDOM_UUID(), 'Squat'),
    (RANDOM_UUID(), 'Deadlift'),
    (RANDOM_UUID(), 'Pull-Up'),
    (RANDOM_UUID(), 'Push-Up'),
    (RANDOM_UUID(), 'Running'),
    (RANDOM_UUID(), 'Cycling'),
    (RANDOM_UUID(), 'Leg Press Machine'),
    (RANDOM_UUID(), 'Chest Press Machine'),
    (RANDOM_UUID(), 'Lat Pulldown Machine'),
    (RANDOM_UUID(), 'Shoulder Press Machine'),
    (RANDOM_UUID(), 'Leg Curl Machine'),
    (RANDOM_UUID(), 'Leg Extension Machine'),
    (RANDOM_UUID(), 'Cable Row Machine'),
    (RANDOM_UUID(), 'Triceps Pushdown Machine'),
    (RANDOM_UUID(), 'Bicep Curl Machine'),
    (RANDOM_UUID(), 'Seated Row Machine'),
    (RANDOM_UUID(), 'Pec Deck Machine'),
    (RANDOM_UUID(), 'Smith Machine Squat'),
    (RANDOM_UUID(), 'Treadmill Running'),
    (RANDOM_UUID(), 'Elliptical Machine'),
    (RANDOM_UUID(), 'Stationary Bike'),
    (RANDOM_UUID(), 'Leg Adduction Machine'),
    (RANDOM_UUID(), 'Leg Abduction Machine');
