name: Build
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
    - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with: 
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=gym-tracker
